#!/bin/bash
set -euo pipefail

PACKAGE_DIR="mdopt"
DOCS_DIR="docs"
SPHINX_SOURCE_DIR="docs/source"
SPHINX_BUILD_DIR="docs/build"
NOTEBOOKS_DEST_DIR="$SPHINX_SOURCE_DIR/notebooks"
API_DEST_DIR="$SPHINX_SOURCE_DIR/api"
EXAMPLES_AUTO_RST="$SPHINX_SOURCE_DIR/examples_auto.rst"
README_RST="$SPHINX_SOURCE_DIR/README.rst"

# Ensure the script is executed from the project root
if [ ! -d "$PACKAGE_DIR" ] || [ ! -d "$DOCS_DIR" ]; then
    echo "Error: Script must be run from the root of the project."
    exit 1
fi

echo "==> Preparing Sphinx source tree"
mkdir -p "$SPHINX_SOURCE_DIR" "$SPHINX_BUILD_DIR" "$NOTEBOOKS_DEST_DIR" "$API_DEST_DIR"

# 1) Convert README.md to README.rst (safe to overwrite)
echo "==> Converting README.md to $README_RST"
pandoc "./README.md" -o "$README_RST"

# 2) Refresh notebooks in docs/source/notebooks (without touching other .rst files)
echo "==> Syncing example notebooks into $NOTEBOOKS_DEST_DIR"
find "$NOTEBOOKS_DEST_DIR" -mindepth 1 -maxdepth 1 -type f -name "*.ipynb" -exec rm -f {} +
if compgen -G "examples/*/*.ipynb" > /dev/null; then
    # Skip notebooks starting with tmp or plotting
    shopt -s nullglob
    for nb in examples/*/*.ipynb; do
        base="$(basename "$nb")"
        if [[ "$base" != tmp* && "$base" != plotting* ]]; then
            cp "$nb" "$NOTEBOOKS_DEST_DIR/"
        fi
    done
    shopt -u nullglob
else
    echo "    (No notebooks found under examples/*/*.ipynb)"
fi

# 3) Generate an auto-index for notebooks WITHOUT touching your curated examples.rst
#    We generate examples_auto.rst and you can link to it from your curated page.
echo "==> Generating $EXAMPLES_AUTO_RST (auto-index of notebooks)"
cat > "$EXAMPLES_AUTO_RST" << 'EOF'
Notebook Examples (auto-generated)
==================================

The following notebooks were discovered and copied from the repository's
``examples/`` directory. This page is auto-generated by the docs build script.
For a curated, tutorial-style set of examples, see :doc:`examples`.

.. toctree::
   :maxdepth: 1
   :caption: Notebooks:

EOF

# Append notebook entries (by filename only; nbsphinx will render them)
if compgen -G "$NOTEBOOKS_DEST_DIR/*.ipynb" > /dev/null; then
    for nb in "$NOTEBOOKS_DEST_DIR"/*.ipynb; do
        echo "   notebooks/$(basename "$nb")" >> "$EXAMPLES_AUTO_RST"
    done
else
    echo "" >> "$EXAMPLES_AUTO_RST"
    echo "*No notebooks found.*" >> "$EXAMPLES_AUTO_RST"
fi

# 4) Generate API .rst files with sphinx-apidoc into docs/source/api
#    IMPORTANT: No --force, so it won't overwrite hand-edited files.
#    Exclude tests and keep a clean, module-first layout.
echo "==> Running sphinx-apidoc into $API_DEST_DIR"
sphinx-apidoc \
    -o "$API_DEST_DIR" \
    "$PACKAGE_DIR" \
    "$PACKAGE_DIR/tests" \
    --separate \
    --module-first

# 5) Clean previous HTML build, then build
echo "==> Cleaning previous builds"
rm -rf "$SPHINX_BUILD_DIR"

echo "==> Building Sphinx documentation"
sphinx-build -b html "$SPHINX_SOURCE_DIR" "$SPHINX_BUILD_DIR"

echo "==> Done. Open: $SPHINX_BUILD_DIR/index.html"
