name: build docs

on: push

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.1.6

    - name: install
      run: poetry install --extras docs

    - name: Build documentation
      run: |
        cd docs/source
        poetry run sphinx-build -b html . _build
