name: docs2pages

on: [push, pull_request, fork]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.1.6

    - name: install
      run: poetry install --extras docs

    - name: Build documentation
      run: |
        cd docs/
        poetry run make html

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: documentation
        folder: _build/html
