name: mypy

on: [push, pull_request, fork]

jobs:
  mypy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5.4.0
          with:
           python-version: 3.10.16

        - name: Set up Poetry
          run: pip install poetry

        - name: Install dependencies
          run: poetry install --with dev

        - name: Run mypy
          run: poetry run mypy mdopt
