name: tests

on: [push, pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up uv and Python 3.11
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync --locked --group test

      - name: Generate report
        run: |
          uv run pytest --cov=./ --cov-report=xml -W ignore::DeprecationWarning

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          use_oidc: true
          files: /home/runner/work/mdopt/mdopt/coverage.xml
          verbose: true
